### ISSUE TITLE
Watch the repository

### ISSUE THREAD

**Issue by NateWr** [NateWr/cyf-faq-group#1]
Everyone in the group should "watch" the repository. GitHub will notify you of new issues and pull requests on the repository when you are watching it, so you can keep track of everyone's work.

![cyf-watch-repo](https://user-images.githubusercontent.com/2306629/30001881-32a5a458-9093-11e7-99c3-1680df44a02f.png)

@panditita, @khaledkzy, @Yjohn, @Habiiba12, @sparkwebdev

**Comment by khaledkzy** [comment]
Done.

**Comment by Yjohn** [comment]
Done

**Comment by sparkwebdev** [comment]
Done
