### ISSUE TITLE
Create Entry data model

### ISSUE THREAD

**Issue by NateWr** [NateWr/cyf-faq-group#2]
@khaledkzy, create an Entry data model using Mongoose. The data model should support:

- questions - string (required)
- answers - string
- how many people found usefull - integers
- how many people found not usefull -integers

Depending on your preference, it can include the total number of useful/not-useful votes too.

**Comment by khaledkzy** [comment]
Good day Everyone, 
this two links are helpful 
https://codeyourfuture.github.io/syllabus-scotland/node-db/lesson5.html
https://codeyourfuture.github.io/syllabus-scotland/node-db/lesson4.html

The data model will look like this;
```
const schema = new Schema({
    question: String,
    answer: String,
    helpful: Number,
    unhelpful: Number
});
```

**Comment by NateWr** [comment]
Thanks @khaledkzy! In the future, you can use three backticks ``` to wrap your code. So three backticks, then some code, then three backticks again. It will make it easier to read. Example:

```
if () {
  ...
}
```

You can also use a single backtick ` to wrap inline code.

That would look like `this`.
